config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  ActiveAdmin.routes(self)
  resources :boxes, ony: [:index, :new, :create] do
    resources :reves, only: [:create]
  end
  resources :reves, only: [:update]
  root 'pages#show', id: 'home'
  get 'a-propos' => 'pages#show', id: 'about', as: 'about'
end

app/models/box.rb
class Box < ActiveRecord::Base
  validates :name, length: { in: 2..30 }
  belongs_to :user
  has_many :reves, class: Reve

  def to_param
    uid
  end
end

app/models/reve.rb
# Reve
class Reve < ActiveRecord::Base
  belongs_to :box
  def self.accepted
    where(accepted: true)
  end

  after_update :update_positions, if: :accepted_changed?

  def update_positions
    self.class.update_positions
  end

  class << self
    def update_positions
      Reve.update_all(position: nil)
      connection.update(
        "UPDATE reves SET position = ranked.rank FROM (#{ranked_sql}) AS ranked WHERE reves.id = ranked.id",
        'Reves accepting re-ordering'
      )
    end

    def ranked_sql
      connection.unprepared_statement do
        ranked.to_sql
      end
    end

    def ranked
      accepted.select('id, rank() OVER (ORDER BY id) AS rank')
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,
         :recoverable, :trackable, :validatable, :registerable
  has_many :boxes
  has_many :reves, through: :boxes, class: Reve
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :new, :create, :edit]
  before_filter :load_box, only: [:show, :edit]

  def index
    @boxes = current_user.boxes
    return redirect_to new_box_path if @boxes.empty?
  end

  def new
    @box = current_user.boxes.new
  end

  def create
    @box = Box.new box_params
    @box.user = current_user
    if @box.save
      redirect_to box_path(id: @box)
    else
      render :new
    end
  end

  def show
    @reve = Reve.find(@box.reves.accepted.pluck(:id).sample)
  end

  def edit

  end

  private

  def load_box
    @box = Box.find_by(uid: params[:id])
  end

  def box_params
    params.require(:box).permit(:name)
  end
end

app/controllers/pages_controller.rb
# PagesController
class PagesController < ApplicationController
  include HighVoltage::StaticPage
end

app/controllers/reves_controller.rb
# RevesController
class RevesController < ApplicationController
  before_filter :authenticate_user!, only: [:update]

  def show
    params[:id] = Reve.accepted.pluck(:position).sample unless params[:id]
    @reve = Reve.find_by_position(params[:id])
  end

  def update
    @reve = current_user.reves.find(params[:id])
    @reve.update!(params.require(:reve).permit(:accepted))
    @reve.reload
  end

  def create
    @box = Box.find_by(uid: params[:box_id])
    @reve = @box.reves.create! reve_params
    flash[:success] = t('reves.created')
    redirect_to box_path(@box)
  end

  def reve_params
    params.require(:reve).permit(:author, :citation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boxes/edit.html.slim
.container-fluid
  .row
    .col-xs-12
      .well
        = link_to box_url(@box), box_path(@box)
  .row
    .col-xs-12
      - @box.reves.each do |reve|
        = render reve

app/views/boxes/index.html.slim
.container-fluid
  .row
    .col-xs-12
      table.table
        thead
          tr
            td Boite
        tbody
          - @boxes.each do |box|
            tr
              td
                = link_to edit_box_path(box)
                  = box.name
      = link_to new_box_path, class: 'btn btn-default' do
        | New Box

app/views/boxes/new.html.slim
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      = simple_form_for(@box) do |f|
        = f.input :name, label: false
        = f.submit class: 'btn btn-primary'

app/views/boxes/show.html.slim
.container-fluid
  .row
    .col-md-4.col-md-offset-4
      p
        = link_to box_path(@box), class: 'reload btn btn-default' do
          | Un autre ?
      = image_tag 'logo.png', class: 'img-responsive'
      blockquote
        h1= @reve.citation
        footer= @reve.author
      /p.contact Plus sur la-boite-a-reves.fr

  .row
    .col-md-4.col-md-offset-4
      = simple_form_for [@box, @box.reves.new] do |f|
        = f.input :citation, label: false, placeholder: 'Reve'
        = f.input :author, label: false, placeholder: 'Auteur'
        = f.submit 'Ajouter un reve', class: 'btn btn-primary'

app/views/layouts/_flash.html.slim
- if flash.any?
  .container-fluid
    .row
      .col-xs-12
        - flash.each do |type, msg|
          = alert_box msg, priority: type

app/views/layouts/_navbar.html.slim
= navbar fluid: true do
  = vertical do
    = link_to t('brand'), root_path
  = horizontal do
    - if user_signed_in?
      = nav do
        = link_to t('.my_boxes'), boxes_path
      = nav class: 'navbar-right' do
        = link_to t('.sign_out'), destroy_user_session_path
    - else
      = nav class: 'navbar-right' do
        = link_to t('devise.sessions.new.sign_in'), new_user_session_path
        = link_to t('devise.registrations.new.sign_up'), new_user_registration_path
    = nav class: 'navbar-right' do
      = link_to t('.about'), about_path

app/views/layouts/application.html.haml
!!!5
%html{html_attrs(:en)}
  %head
    %meta{:charset => "utf-8"}
    - title = 'La boite a reves'
    %title= title.html_safe
    %meta{ name: 'description', content: title}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Ubuntu", media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{class: body_class}
    = render 'layouts/navbar'
    = render 'layouts/flash'
    = yield

app/views/pages/about.html.slim
.container-fluid.about
  .row
    .col-md-4.col-md-offset-1
      = image_tag 'boite.jpg', class: 'img-responsive'
    .col-md-5.col-md-offset-1
      h1 A Propos
      p
        |Développé en un weekend, le principe est simple: permettre aux utilisateurs de s'évader quelques instants.
        |Une petite pièce insérée dans la boite à rêves au look retro, et quelques pixels de rêve s'impriment.
        |De quoi sourire et repartir avec un instant de bonheur en poche.

      p Entre mondes réel et virtuel, cette bonne humeur se développe aussi sur la toile, où il vous est possible d'ajouter une citation de votre choix, afin qu'elle apparaisse au plus vite dans la boite à rêve.
      p Une façon originale de partager des sourires !

      -# Et pour que ces petits bonheurs se répandent encore plus joyeusement, les bénéfices sont reversés à une association solidaire.
      p Partez à la recherche de la boite à rêves, elle se cache dans Paris ou contactez-nous :
      = link_to 'contact@la-boite-a-reves.fr', 'mailto:contact@la-boite-a-reves.fr'

      -# les couloirs du métro parisien… ( pluriel pour les boites a reves? )
      .row.team
        .col-xs-4
          = image_tag 'luc.jpg', class: 'img-responsive'
          p Luc
        .col-xs-4
          = image_tag 'martin.jpg', class: 'img-responsive'
          p Martin
        .col-xs-4
          = image_tag 'guillaume.jpg', class: 'img-responsive'
          p Guillaume

app/views/pages/home.html.slim
.container-fluid
  .row
    .col-md-4.col-md-offset-1
      = image_tag 'boite.jpg', class: 'img-responsive'
    .col-md-4.col-md-offset-2
      a.btn.btn-lg.btn-primary
        .fa.fa-star
        | La Boite a sourires
    /.col-md-4.col-md-offset-2
      .well
        = image_tag 'logo.png', class: 'img-responsive'
        - @reve = Reve.find(Reve.where(box: nil).accepted.pluck(:id).sample)
        blockquote
          h1= @reve.citation
          footer= @reve.author
        - if params[:print]
          p.contact Plus sur la-boite-a-reves.fr

app/views/reves/_reve.html.slim
a.reve-item href=refe_path(reve, reve: { accepted: !reve.accepted }) id="reve-#{reve.id}" class=('accepted' if reve.accepted) data-remote=true data-method="put"
  blockquote.reve
    = reve.citation
    footer= reve.author

app/views/reves/show.html.slim
.containter
  .row
    .col-md-4.col-md-offset-4
      - unless params[:print]
        p
          = link_to about_path, class: 'btn btn-default' do
            | A Propos
          = link_to root_path, class: 'reload btn btn-default' do
            | Un autre ?
      = image_tag 'logo.png', class: 'img-responsive'
      blockquote
        h1= @reve.citation
        footer= @reve.author
      /- if params[:print]
        p.contact Plus sur la-boite-a-reves.fr

    - unless params[:print]
      .col-md-4.col-md-offset-4
        = simple_form_for Reve.new do |f|
          = f.input :citation, label: false, placeholder: 'Reve'
          = f.input :author, label: false, placeholder: 'Auteur'
          = f.submit 'Ajouter un reve', class: 'btn btn-primary'

app/views/reves/update.js.erb
$('#reve-<%= @reve.id %>').replaceWith('<%= j render(@reve) %>')